server:
  port: 8082

spring:
  application:
    name: write-api
  #mybatis配置
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/cinema?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver



  mvc:
#    hiddenmethod:
#      filter:
#        enabled=true:
    pathmatch:
      matching-strategy: ant_path_matcher

  #springredis配置
  redis:
    host: localhost
    port: 6379
    database: 0

#mybatis配置
mybatis:
  type-aliases-package: model.entity
  mapper-locations: classpath:mapper/*.xml

#logging:
#  level:
#    com:
#      cai:
#        library:
#          mapper: debug

#eureka配置
eureka:
  client:
    #表示是否将自己注册进eureka  默认为true
    register-with-eureka: true
    #是否从EurekaServer中抓取已有的注册信息，默认为true，单点无所谓，集群必须设置true才能和ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #单机配置
      defaultZone: http://localhost:7001/eureka